# Generated by Django 5.2.4 on 2025-08-07 21:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="timestamp",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(
                    2025, 8, 7, 21, 13, 58, 932211, tzinfo=datetime.timezone.utc
                ),
            ),
            preserve_default=False,
        ),
    ]
