# Generated by Django 5.2.4 on 2025-08-10 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_attendance_collectormetricscache_routepoint"),
    ]

    operations = [
        migrations.CreateModel(
            name="AnalyticsSummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("generated_on", models.DateTimeField(auto_now_add=True)),
                ("total_revenue", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "avg_daily_revenue",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("top_collector", models.CharField(max_length=100)),
                ("highest_area", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="ForecastRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("forecast_date", models.DateField()),
                (
                    "predicted_revenue",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("confidence_interval", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="FraudAlert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("transaction_id", models.CharField(max_length=50)),
                ("reason", models.TextField()),
                ("detected_on", models.DateTimeField(auto_now_add=True)),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                        ],
                        max_length=20,
                    ),
                ),
            ],
        ),
    ]
