# Generated by Django 5.2.4 on 2025-08-10 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_analyticssummary_forecastrecord_fraudalert"),
    ]

    operations = [
        migrations.CreateModel(
            name="RevenueRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("collector", models.CharField(max_length=100)),
                ("category", models.CharField(max_length=100)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
    ]
