# Generated by Django 5.2.4 on 2025-08-16 12:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_revenuerecord"),
    ]

    operations = [
        migrations.RenameField(
            model_name="payment",
            old_name="location",
            new_name="paystack_reference",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="date",
        ),
        migrations.AddField(
            model_name="payment",
            name="full_name",
            field=models.CharField(default="ghana", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="payment",
            name="igf_type",
            field=models.CharField(
                choices=[
                    ("rates", "Rates"),
                    ("fees", "Fees"),
                    ("fines", "Fines"),
                    ("licenses", "Licenses"),
                    ("rents", "Rents"),
                    ("investment_income", "Investment Income"),
                    ("tender_docs", "Sales of Tender Documents"),
                    ("business_taxes", "Business Taxes"),
                    ("permits", "Permits"),
                ],
                default="fees",
                max_length=30,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="payment",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("success", "Success"),
                    ("failed", "Failed"),
                ],
                db_index=True,
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="collector",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="method",
            field=models.CharField(
                choices=[("paystack", "Paystack"), ("cash", "Cash")], max_length=20
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="timestamp",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
