# Generated by Django 5.2.4 on 2025-08-16 14:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_business_registered_via_payment_latitude_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="date",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(
                    2025, 8, 16, 14, 49, 45, 108159, tzinfo=datetime.timezone.utc
                ),
            ),
            preserve_default=False,
        ),
    ]
