# Generated by Django 5.2.4 on 2025-08-17 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_businessowner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("collector", "Collector"),
                    ("admin", "Admin"),
                    ("business", "Business Owner"),
                ],
                max_length=20,
            ),
        ),
    ]
