# Generated by Django 5.2.4 on 2025-08-17 14:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_alter_user_role"),
    ]

    operations = [
        migrations.CreateModel(
            name="BusinessOwnerProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mobile_money_number", models.CharField(max_length=15)),
                (
                    "network",
                    models.CharField(
                        choices=[
                            ("mtn", "MTN"),
                            ("vodafone", "Vodafone"),
                            ("airteltigo", "AirtelTigo"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "onboarding_status",
                    models.CharField(
                        choices=[("pending", "Pending"), ("active", "Active")],
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="owners",
                        to="core.business",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
