# Generated by Django 5.2.4 on 2025-08-17 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_businessownerprofile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="businessownerprofile",
            name="mobile_money_number",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
