# Generated by Django 5.2.4 on 2025-08-17 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_businesspayment"),
    ]

    operations = [
        migrations.AddField(
            model_name="businessowner",
            name="business_name",
            field=models.CharField(default="takoradi", max_length=255),
            preserve_default=False,
        ),
    ]
