# Generated by Django 5.2.4 on 2025-08-17 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_businessowner_business_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="business",
            name="latitude",
            field=models.DecimalField(
                blank=True, decimal_places=8, max_digits=11, null=True
            ),
        ),
        migrations.AlterField(
            model_name="business",
            name="longitude",
            field=models.DecimalField(
                blank=True, decimal_places=8, max_digits=11, null=True
            ),
        ),
    ]
