# Generated by Django 5.2.4 on 2025-08-19 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_alter_business_latitude_alter_business_longitude"),
    ]

    operations = [
        migrations.AddField(
            model_name="businessowner",
            name="company_name",
            field=models.CharField(default="test", max_length=255),
            preserve_default=False,
        ),
    ]
