# Generated by Django 5.2.4 on 2025-08-19 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_businessowner_company_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="businessowner",
            name="company_name",
        ),
    ]
