# Generated by Django 5.2.4 on 2025-08-19 20:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0018_remove_businessowner_company_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="business",
            name="owner",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="business",
                to="core.businessowner",
            ),
        ),
    ]
