# Generated by Django 5.2.4 on 2025-08-19 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0019_business_owner"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="business",
            name="owner",
        ),
    ]
