# Generated by Django 5.2.4 on 2025-08-19 22:28

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0020_remove_business_owner"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="businessowner",
            options={
                "ordering": ["business_name"],
                "verbose_name": "Business Owner",
                "verbose_name_plural": "Business Owners",
            },
        ),
        migrations.AddField(
            model_name="businessowner",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="businessowner",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="businessowner",
            name="business_name",
            field=models.CharField(max_length=255, verbose_name="Business Name"),
        ),
        migrations.AlterField(
            model_name="businessowner",
            name="latitude",
            field=models.DecimalField(
                decimal_places=6, max_digits=9, verbose_name="Latitude"
            ),
        ),
        migrations.AlterField(
            model_name="businessowner",
            name="location",
            field=models.CharField(max_length=255, verbose_name="Business Location"),
        ),
        migrations.AlterField(
            model_name="businessowner",
            name="longitude",
            field=models.DecimalField(
                decimal_places=6, max_digits=9, verbose_name="Longitude"
            ),
        ),
        migrations.AlterField(
            model_name="businessowner",
            name="phone_number",
            field=models.CharField(
                max_length=17,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Phone number must be entered in the format: '0123456789'. Up to 15 digits allowed.",
                        regex="^\\+?\\d{9,15}$",
                    )
                ],
                verbose_name="Phone Number",
            ),
        ),
        migrations.AlterField(
            model_name="businessowner",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="business_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
