# Generated by Django 5.2.4 on 2025-08-19 22:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0021_alter_businessowner_options_businessowner_created_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BusinessOwnerPayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=100)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("success", "Success"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "igf_type",
                    models.CharField(
                        choices=[
                            ("rates", "Rates"),
                            ("fees", "Fees"),
                            ("fines", "Fines"),
                            ("licenses", "Licenses"),
                            ("rents", "Rents"),
                            ("investment_income", "Investment Income"),
                            ("tender_docs", "Sales of Tender Documents"),
                            ("business_taxes", "Business Taxes"),
                            ("permits", "Permits"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "paystack_reference",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "receipt_id",
                    models.CharField(blank=True, max_length=100, unique=True),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="paystack_payments",
                        to="core.business",
                    ),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="submitted_payments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Business Owner Payment",
                "verbose_name_plural": "Business Owner Payments",
                "ordering": ["-timestamp"],
            },
        ),
    ]
