# Generated by Django 5.2.4 on 2025-08-19 23:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0022_businessownerpayment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="businessownerpayment",
            name="business",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="paystack_payments",
                to="core.businessowner",
            ),
        ),
    ]
