# Generated by Django 5.2.4 on 2025-08-20 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0023_alter_businessownerpayment_business"),
    ]

    operations = [
        migrations.AlterField(
            model_name="businessowner",
            name="latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="businessowner",
            name="longitude",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
