# Generated by Django 5.2.4 on 2025-08-25 00:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0024_alter_businessowner_latitude_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BusinessOwnerRevenueRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "igf_type",
                    models.CharField(
                        choices=[
                            ("rates", "Rates"),
                            ("fees", "Fees"),
                            ("fines", "Fines"),
                            ("licenses", "Licenses"),
                            ("rents", "Rents"),
                            ("investment_income", "Investment Income"),
                            ("tender_docs", "Sales of Tender Documents"),
                            ("business_taxes", "Business Taxes"),
                            ("permits", "Permits"),
                        ],
                        max_length=30,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "business_owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="revenue_records",
                        to="core.businessowner",
                    ),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
